CREATE TABLE OLIST_ECOMMERCE.RAW.raw_customers(
	CUSTOMER_ID VARCHAR(64),
	CUSTOMER_UNIQUE_ID VARCHAR(64),
	CUSTOMER_ZIP_CODE_PREFIX VARCHAR(12),
	CUSTOMER_CITY VARCHAR(50),
	CUSTOMER_STATE VARCHAR(50)
)
